### PR TITLE
Python3 Porting [GCI]

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by srevinsaju** [comment]
@quozl @chimosky please review

**Comment by quozl** [comment]
Thanks.  Does it work?  What results from coverage testing?

**Comment by srevinsaju** [comment]
@quozl coverage 42%. Tested, it does works and I can save files too. capture and record both works very good.

**Comment by quozl** [comment]
Audio recording is expected to work.  But have you taken photographs?  Have you made videos?  Have you been able to resume a journal object with a set of recordings?

**Comment by srevinsaju** [comment]
Yes @quozl I tested videos and photos, I can send them if you want, but I don't know where `sugar3.datastore` saves files on the Fedora system.

**Comment by quozl** [comment]
Journal activity, which is part of Sugar, provides user interface to journal objects.  Please use that for testing.  You should be able to view the Journal with the F5 key, and then open one of the previous Record sessions by clicking on it.  Each of the recordings should be presented again.  It is critical to test this, because that's how children will use the activity.

**Comment by srevinsaju** [comment]
Yes, i have it in journal, my screenshots too are in journal, I am thinking a way to send it to you.

**Comment by quozl** [comment]
So you have been able to resume a journal object with a set of recordings and they are presented for playback?

**Comment by quozl** [comment]
I've tried taking a photograph, stopping the activity, and resuming the Record instance from Journal.  The photograph is not shown.  Logs suggest a reason;

```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sugar3/activity/activity.py", line 743, in __canvas_map_cb
    self.read_file(self._jobject.file_path)
  File "/usr/share/sugar/activities/Record.activity/record.py", line 147, in read_file
    self.model.read_file(path)
  File "/usr/share/sugar/activities/Record.activity/model.py", line 96, in read_file
    serialize.fillMediaHash(dom, self.mediaHashs)
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 43, in fillMediaHash
    _loadMediaIntoHash(el, mediaHashs[key])
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 49, in _loadMediaIntoHash
    recd = fillRecdFromNode(recd, el)
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 151, in fillRecdFromNode
    thumbImg = utils.getPixbufFromString(bt.nodeValue)
  File "/usr/share/sugar/activities/Record.activity/utils.py", line 43, in getPixbufFromString
    data = base64.b64decode(str)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```

**Comment by srevinsaju** [comment]
Ok, I didn't try loading it from the Journal, I only got the captured image in the journal. Thanks for reviewing. I will add that to my checklist for future activities

**Comment by srevinsaju** [comment]
Ok @quozl , fixed it on https://github.com/sugarlabs/record-activity/pull/24/commits/81e3c7079d802ac8e4da310c1d87f51b7f38eb5c

**Comment by quozl** [comment]
I've tested 81e3c70 in the same scenario, and wasn't able to see the captured image on resume;

```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sugar3/activity/activity.py", line 743, in __canvas_map_cb
    self.read_file(self._jobject.file_path)
  File "/usr/share/sugar/activities/Record.activity/record.py", line 147, in read_file
    self.model.read_file(path)
  File "/usr/share/sugar/activities/Record.activity/model.py", line 96, in read_file
    serialize.fillMediaHash(dom, self.mediaHashs)
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 43, in fillMediaHash
    _loadMediaIntoHash(el, mediaHashs[key])
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 49, in _loadMediaIntoHash
    recd = fillRecdFromNode(recd, el)
  File "/usr/share/sugar/activities/Record.activity/serialize.py", line 151, in fillRecdFromNode
    thumbImg = utils.getPixbufFromString(bt.nodeValue)
  File "/usr/share/sugar/activities/Record.activity/utils.py", line 44, in getPixbufFromString
    pbl.write(data)
GLib.Error: gdk-pixbuf-error-quark: Unrecognized image file format (3)
```

**Comment by srevinsaju** [comment]
@quozl I almost took a week to fix this error, the change is small. Please review

**Pull request merged**
