### PR TITLE
Updated License and Copyright

### LINKED ISSUE #2: incomplete copyright and licensing info
This project has incomplete and arguably misleading copyright and licensing info:

COPYING contains the Expat license which might wrongly lead some to believe the project as a whole having that license: Some files are licensed as LGPL-2 and some as GPL-2+ which the Expat-licensed parts can be "upgraded" to but not the reverse, so arguably render the project as a whole can be licensable only as GPL-2+

aplay.py contains licensing but lacks copyright: Who is the copyright holder who issued that licensing?

hw.py and tray.py is licensed as non-existent _Lesser_ GPL 2 (LGPL pror to 2.1 was called _Library_ GPL), and claims the actual license is included with the project which it isn't.

aplay.py and setup.py is licensed as GPL 2 , and claims the actual license is included with the project which it isn't.

Several files - in particular code files - lack both copyright and licensing: If they are supposed to inherit the licensing of COPYING file then I believe that needs to be stated explicitly somewhere.

I recommend to list copyright line(s) in each and every code file, and include Expat licensing with each file licensed as such, and put GPL 2 in COPYING file, and add COPYING.lgpl with License GPL 2 licensing.

### PR DESCRIPTION
**Pull request by yatinmaan**
Updated the license on all code files to expat license.
fixes #2

### CODE REVIEW

**Comment by quozl** [comment]
This patch changes the license on some work that I assigned to One Laptop per Child, and I'm still with them, and I don't agree with the change.

What this patch does was not the action plan proposed by @jonassmedegaard in #2:

> I recommend to list copyright line(s) in each and every code file, and include Expat licensing with each file licensed as such, and put GPL 2 in COPYING file, and add COPYING.lgpl with License GPL 2 licensing.

Is there some reason that this plan cannot be followed?

**Comment by yatinmaan** [comment]
I misunderstood his plan. I will revert the copyrights to their original form.

Should I upgrade GNU to expat ?
What license and copyright should I add to the files that don't have any ?

**Comment by jonassmedegaard** [comment]
Quoting yatinmaan (2016-11-14 08:17:11)

> I misunderstood his plan. I will revert the copyrights to their original form.
> 
> Should I upgrade GNU to expat ?

That sentence does not make sense.  You probably mean either "rename" or 
"relicense", or both...

About license _names_:

"GNU" is a software movement, who formulated several general public 
licenses, where the most common and their recommended one for software 
projects is the GNU General Public License.  Commonly that license is 
named "te GNU GPL license" or just "the GPL license".

"Expat" is a code project, which is licensed with a general public 
license formulated by MIT.  Commonly that license is named "the MIT 
license". Some argue, however, that MIT has formulated many licenses 
with varying licensing terms, and recommend to instead name it "the 
Expat license" to avoid misunderstandings (as the very purpose of 
licensing is to explicitly declare specific permissions).

About license _grant_:

Only the owner of a piece of software - its copyright holder - can 
declare permissions for other - grant a license.

About renaming and/or relicensing:

if you ask what _name_ is advicable use for an existing license, then I 
recommend to say "Expat" instead of "MIT", and say "GPL" instead of 
"GNU" - after double-checking that indeed those are the licenses you 
talk about.

If you ask what license is best, then my personal political opinion is 
that GPL is best, and I suggest that you consider to license your works 
as GPL instead of Expat.  But that is _only_ for code you are copyright 
holder for.  For code that you borrow from others, you are bound by the 
license that _they_ granted to _you_ - and maybe that license allows you 
to relicense, but maybe it does not.

If you ask if it is ok to relicense some code owned by others, that they 
licensed as GPL, to instead be licensed as Expat, then the answer is no: 
Expat license contain less rules than GPL, and the GPL license require 
that you preserve all of its rules when you pass it on to others.

(GPL is a "copyleft" license where the jargon is that you get "freedoms" 
that you may keep as long as you grant the same (or more) freedoms if 
you pass it on to others - Expat is a "permissive" license where jargon 
is that copyleft is infections you cannot cure the code from again.)

> What license and copyright should I add to the files that don't have 
> any ?

If you own the code, you can choose freely, and I suggest GPL.

If you are not owner (but redistributor, custodian, remixer, co-author 
etc.) then you must ask the owner of the code what license they grant.  
You are not allowed to add or change a license without the permission of 
the code owner.  You are not even allowed to distribute without getting 
permission from the code owner, so you _must_ ask the owner!
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by yatinmaan** [comment]
> Should I upgrade GNU to expat ?

I meant `Should I "upgrade" GPL to expat ?` , sorry for the confusion.

I don't have any rights to this code. That's why I was asking @quozl for direction on files that don't already have any Copyrights and Licenses on them.

**Comment by jonassmedegaard** [comment]
Quoting yatinmaan (2016-11-15 14:59:30)

> > Should I upgrade GNU to expat ?
> > I meant `Should I _"upgrade"_ GPL to expat ?` , sorry for the confusion.

If by the quotes you mean really-a-downgrade-from-POV-of-GPL-lovers then 
I agree.

> I don't have any rights to this code. That's why I was asking @quozl 
> for direction on files that don't already have any Copyrights and 
> Licenses on them.

Thanks for the clarification.  I will leave it to @quozl to deal with 
his code.
- Jonas

## 
- Jonas Smedegaard - idealist & Internet-arkitekt
- Tlf.: +45 40843136  Website: http://dr.jones.dk/
  
  [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by quozl** [comment]
What these patches (1e66951, 2ef05b4) do was not the action plan proposed by @jonassmedegaard in #2:

> I recommend to list copyright line(s) in each and every code file, and include Expat licensing with each file licensed as such, and put GPL 2 in COPYING file, and add COPYING.lgpl with License GPL 2 licensing.

Is there some reason that this plan cannot be followed?

Instead, what you have done (which was not in the commit message by the way), was;
- add Expat license to several files,
- remove the coding tag from constants.py,
- assigned the copyright of aplay.py to the original authors.

Good start, but my expectation also includes;
- add a copyright Aleksey Lim to aplay.py, (see 4ef0507 for provenance), unless you have contact with Aleksey to say otherwise,
- put exact text of GPL2 in COPYING file, replacing what is there,
- change from 'Lesser' to 'Library' in hw.py and tray.py,
- put exact text of LGPL2 in COPYING.lgpl

Hope that helps!

**Comment by yatinmaan** [comment]
I didn't mean to push the last two commits, I did that by mistake. I am new to GitHub.
Should I do something about the files which don't contain any license or copyright information ?

**Comment by quozl** [comment]
Thanks.

The *Files changed* tab of your pull request does complete the action plan; consisting of 3d2d8d4880a2e7bd0e598c927826275eaed7faad, fbe61719995f8aa90b885c4ba5aaa32ac9f4e73d, 1e66951d17a1346a9191a2c6d4594e219d95e715, 2ef05b4c2552467609eb6338ecf936cb380af956, a7a0f8d614a18dec5b85de3df06e1a06e0190ce5, a1c6dd332a9b00027442ad859f945a0674482c93, and 367a8db2364dd4250459ab2f77026f9b4a039ce7.

However, some of these commits revert some of the others.  If this were merged, our repository would contain each commit, which is unnecessary and time consuming in future.  Could you please

- [ ] rebase to squash your seven (7) commits into one,

You may find these resources useful;
- https://help.github.com/articles/about-git-rebase/
- https://help.github.com/articles/using-git-rebase-on-the-command-line/

**Comment by yatinmaan** [comment]
Done.
Thanks for your help.

**Comment by quozl** [comment]
@yatimaan, thanks, I've built on your work and opened pull request https://github.com/sugarlabs/record-activity/pull/12 so please review and comment there.

Pull request #11 can be closed now.

**Pull request closed without merging**
