### PR TITLE
V201

### PR DESCRIPTION
**Pull request by chimosky**
@quozl kindly review, a tag exists.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

* [x] 8c75a5f says new translations, but it also contains a version number change; the version number change would be best enclosed in 73a16ff.
* [x] 8c75a5f has a lot of changes to Plural-Forms; did you expect this?  I had to remove them before.  See 64d6e35 ("Remove plural forms from translations").

You may be interested to compare with a3703c3 ("Remove empty translations") and 46f3fd1 ("translate.sugarlabs.org synchronisation") from a few weeks ago on the _fedora18_ branch.  I don't think the POT file updates are reaching the translation web site, so the translations are the same.

**Comment by chimosky** [comment]
> - [ ]  8c75a5f says new translations, but it also contains a version number change; the version number change would be best enclosed in 73a16ff.

Yeah I'd missed that, thanks.

> - [ ]  8c75a5f has a lot of changes to Plural-Forms; did you expect this? I had to remove them before. See 64d6e35 ("Remove plural forms from translations").

Wasn't expecting that.

>  I don't think the POT file updates are reaching the translation web site, so the translations are the same.

The last translation for record activity was done two years ago, that's why they're no updates in translations.

**Comment by quozl** [comment]
> > I don't think the POT file updates are reaching the translation web site, so the translations are the same.
> 
> The last translation for record activity was done two years ago, that's why they're no updates in translations.

No, it's not that simple.

If you `git grep POT-Creation-Date` you can see that despite the `Record.pot` file being changed, the translators are not being asked to translate the new or changed strings.  The most recent translation work on _pt_BR_ was 2018-09-03 and based on the template at 2017-03-24.  Template change in 2018-06-15 in 5709f92a282ad7cbd5dc97fa8656a463a962eafb didn't reach the translators.

So I'd say the biggest reason for no updates is that we haven't been able to get the template file to the translators.

**Comment by chimosky** [comment]
> So I'd say the biggest reason for no updates is that we haven't been able to get the template file to the translators.

I agree, we can let Chris know about the changes when that happens.

**Pull request merged**
