### PR TITLE
Refresh POT, synch with Pootle, trim headers/footers

### PR DESCRIPTION
**Pull request by leonardcj**

### CODE REVIEW

**Comment by quozl** [comment]
Causes my build to fail;

```
ValueError: plural forms expression could be dangerous
```

FTBFS

**Comment by quozl** [comment]
@leonardcj, any idea what causes this?  I just stumbled across it again, and will pull the patch from my build.

**Comment by leonardcj** [comment]
Does it traceback to hy.po?  This PO seems to show a pluralforms error on Pootle, but I can't see it in the file itself.

**Comment by quozl** [comment]
Thanks, good idea.  Reapplying the patch, reversing the `po/hy.po` changes, does not fix.

Several of the changes in the commit add a line

```
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\n"
```

according to some tickets this is a trigger for the error, yet these lines don't cause problems everywhere; in particular in `sugar-toolkit-gtk3`, but this could be because the tool chain differs.  

Searching all my activity repositories only Record has `plural=EXPRESSION`.

On the other hand, an answer on [this stackoverflow question](http://stackoverflow.com/questions/41924444/how-to-fix-plural-forms-could-be-dangerous-django-error) suggests the `n != 1` form is dangerous.

So my guess is both must be ejected via the airlock.

**Pull request merged**
